[package]
edition = "2018"
name = "udedokei"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]

[dependencies]
tokei = "10.1.0"
ignore = "0.4.10"
serde = "1.0.104"
serde_derive = "1.0.104"
