[package]
edition = "2021"
name = "udedokei"
version = "0.1.1"
authors = ["Kornel <kornel@geekhood.net>"]
publish = false

[dependencies]
tokei = "12.1.2"
ignore = "0.4.18"
serde = "1.0.145"
serde_derive = "1.0.145"
ahash = "0.8.0"

[badges]
maintenance = { status = "as-is" }
