[package]
edition = "2018"
name = "simple_cache"
version = "0.6.0"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Minimal wrapper for a HTTP client to cache results on disk, forever"
license = "CC0-1.0"

[dependencies]
reqwest = "0.9"
quick-error = "1.2.2"
serde_json = "1.0.20"
serde = "1.0.66"
rusqlite = "0.16"
thread_local = "0.3.6"
bincode = "1.0.1"
tempfile = "3.0.3"
rmp-serde = "0.13.7"
