
[workspace]
members = [
"cargo_author",
"cargo_toml",
"categories",
"crate_db",
"crate_files",
"crates_io_client",
"docs_rs_client",
"front_end",
"github_info",
"kitchen_sink",
"lazyonce",
"reindex",
"render_readme",
"repo_url",
"rich_crate",
"simple_cache",
"user_db",
"crate_git_checkout",
]

[profile.dev]
opt-level = 1

[patch.crates-io]
cargo_toml = { path = "cargo_toml" }
cargo_author = { path = "cargo_author" }
lazyonce = { path = "lazyonce" }
onig_sys = { git = "https://github.com/rust-onig/rust-onig.git", default-features = false }
rusqlite = { git = "https://github.com/jgallagher/rusqlite.git" }

[patch.'https://gitlab.com/crates.rs/categories.git']
categories = { path = "categories" }

[patch.'https://gitlab.com/crates.rs/crate_db.git']
crate_db = { path = "crate_db" }

[patch.'https://gitlab.com/crates.rs/crate_files.git']
crate_files = { path = "crate_files" }

[patch.'https://gitlab.com/crates.rs/crate_git_checkout.git']
crate_git_checkout = { path = "crate_git_checkout" }

[patch.'https://gitlab.com/crates.rs/crates_io_client.git']
crates_io_client = { path = "crates_io_client" }

[patch.'https://gitlab.com/crates.rs/docs_rs_client.git']
docs_rs_client = { path = "docs_rs_client" }

[patch.'https://gitlab.com/crates.rs/front_end.git']
front_end = { path = "front_end" }

[patch.'https://gitlab.com/crates.rs/github_info.git']
github_info = { path = "github_info" }

[patch.'https://gitlab.com/crates.rs/kitchen_sink.git']
kitchen_sink = { path = "kitchen_sink" }

[patch.'https://gitlab.com/crates.rs/reindex.git']
reindex = { path = "reindex" }

[patch.'https://gitlab.com/crates.rs/render_readme.git']
render_readme = { path = "render_readme" }

[patch.'https://gitlab.com/crates.rs/repo_url.git']
repo_url = { path = "repo_url" }

[patch.'https://gitlab.com/crates.rs/rich_crate.git']
rich_crate = { path = "rich_crate" }

[patch.'https://gitlab.com/crates.rs/simple_cache.git']
simple_cache = { path = "simple_cache" }

[patch.'https://gitlab.com/crates.rs/user_db.git']
user_db = { path = "user_db" }
