
[workspace]
members = [
"builder",
"cargo_author",
"cargo_toml",
"categories",
"crate_db",
"crates_io_client",
"datadump",
"docs_rs_client",
"front_end",
"github_info",
"kitchen_sink",
"reindex",
"render_readme",
"repo_url",
"rich_crate",
"simple_cache",
"user_db",
"crate_git_checkout",
"udedokei",
"search_index",
"ranking",
"server",
"deps_index",
"render_readme/dump",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[profile.dev.package.miniz_oxide]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.serde]
opt-level = 3

[profile.dev.package.rmp-serde]
opt-level = 3


[patch.crates-io]
cargo_toml = { path = "cargo_toml" }
cargo_author = { path = "cargo_author" }
onig = { git = "https://github.com/kornelski/rust-onig" }
onig_sys = { git = "https://github.com/kornelski/rust-onig" }

[patch.'https://gitlab.com/crates.rs/render_readme.git']
render_readme = { path = "render_readme" }
