[package]
name = "rich_crate"
version = "0.2.2"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Crate struct enriched with additional crates.rs metadata"
license = "Apache-2.0 OR MIT"

[dependencies]
crates-index = "0.12.0"
crates_io_client = { git = "https://gitlab.com/crates.rs/crates_io_client.git" }
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git" }
categories = { git = "https://gitlab.com/crates.rs/categories.git" }
cargo_author = "1.0.0"
cargo_toml = "0.3.0"
repo_url = { git = "https://gitlab.com/crates.rs/repo_url.git" }
semver = "0.9.0"
parse_cfg = "1.0.1"
