[package]
name = "front_end"
version = "0.2.0"
authors = ["Kornel <kornel@geekhood.net>"]
autobins = true

[lib]
name = "front_end"
path = "src/front_end.rs"

[build-dependencies]
ructe = "0.3.16"

[dependencies]
kitchen_sink = { git = "https://gitlab.com/crates.rs/kitchen_sink.git" }
rich_crate = { git = "https://gitlab.com/crates.rs/rich_crate.git" }
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git" }
categories = { git = "https://gitlab.com/crates.rs/categories.git" }
rayon = "1.0.1"
failure = "0.1.1"
chrono = "0.4.2"
semver = "0.9.0"
lab = "0.4.3"
urlencoding = "1.0.0"
regex = "1.0.0"
