
[workspace]
members = [
"builder",
"cargo_author",
"cargo_toml",
"categories",
"crate_db",
"crates_io_client",
"docs_rs_client",
"front_end",
"github_info",
"kitchen_sink",
"lazyonce",
"reindex",
"render_readme",
"repo_url",
"rich_crate",
"simple_cache",
"user_db",
"crate_git_checkout",
"udedokei",
"search_index",
"ranking",
"server",
"render_readme/dump",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[patch.crates-io]
cargo_toml = { path = "cargo_toml" }
cargo_author = { path = "cargo_author" }
lazyonce = { path = "lazyonce" }
rmp = { git = "https://github.com/3Hren/msgpack-rust", rev = "b93ea78dcb1c0326a3195790cbbad9dda16e7027" }
rmp-serde = { git = "https://github.com/3Hren/msgpack-rust", rev = "b93ea78dcb1c0326a3195790cbbad9dda16e7027" }
onig = { git = "https://github.com/kornelski/rust-onig" }
onig_sys = { git = "https://github.com/kornelski/rust-onig" }

[patch.'https://gitlab.com/crates.rs/crate_git_checkout.git']
crate_git_checkout = { path = "crate_git_checkout" }

[patch.'https://gitlab.com/crates.rs/crates_io_client.git']
crates_io_client = { path = "crates_io_client" }

[patch.'https://gitlab.com/crates.rs/docs_rs_client.git']
docs_rs_client = { path = "docs_rs_client" }

[patch.'https://gitlab.com/crates.rs/render_readme.git']
render_readme = { path = "render_readme" }

[patch.'https://gitlab.com/crates.rs/repo_url.git']
repo_url = { path = "repo_url" }

[patch.'https://gitlab.com/crates.rs/simple_cache.git']
simple_cache = { path = "simple_cache" }

