[package]
name = "docs_rs_client"
version = "0.2.0"
authors = ["Kornel <kornel@geekhood.net>"]

[lib]
name = "docs_rs_client"
path = "src/lib_docs_rs_client.rs"

[dependencies]
quick-error = "1.2.1"
serde = "1.0.45"
serde_json = "1.0.17"
serde_derive = "1.0.45"
simple_cache = { git = "https://gitlab.com/crates.rs/simple_cache.git" }
