[package]
description = "Analyze git repository containing Cargo crates"
name = "crate_git_checkout"
version = "0.2.1"
authors = ["Kornel <kornel@geekhood.net>"]

[lib]
name = "crate_git_checkout"
path = "src/crate_git_checkout.rs"

[dependencies]
git2 = "0.7.2"
cargo_toml = "0.3.1"
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git" }
repo_url = { git = "https://gitlab.com/crates.rs/repo_url.git" }
failure = "0.1.1"
urlencoding = "1.0.0"
