[package]
name = "crate_files"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]

[dependencies]
tar = "0.4.15"
libflate = "0.1.14"
cargo_toml = "0.3.0"
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git" }
repo_url = { git = "https://gitlab.com/crates.rs/repo_url.git" }
toml = "0.4.6"
quick-error = "1.2.2"
