[package]
version = "0.8.0"
edition = "2018"
name = "crates_io_client"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Unofficial, minimal client that gets data from crates.io internal JS API"

[lib]
name = "crates_io_client"
path = "src/lib_crates_io_client.rs"

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
simple_cache = { git = "https://gitlab.com/crates.rs/simple_cache.git", version = "0.7.0" }
rand = "0.7.2"
semver = "0.9.0"
parking_lot = "0.10.0"
rayon = "1.3.0"
urlencoding = "1.0.0"
