
[workspace]
members = [
"cargo_author",
"cargo_toml",
"categories",
"crate_db",
"crate_files",
"crates_io_client",
"docs_rs_client",
"front_end",
"github_info",
"kitchen_sink",
"lazyonce",
"reindex",
"render_readme",
"repo_url",
"rich_crate",
"simple_cache",
"user_db",
"crate_git_checkout",
"udedokei",
"search_index",
"ranking",
"server",
"render_readme/dump",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[patch.crates-io]
cargo_toml = { path = "cargo_toml" }
cargo_author = { path = "cargo_author" }
lazyonce = { path = "lazyonce" }
rmp = { git = "https://github.com/kornelski/msgpack-rust", rev = "1a05988fb11d73d2e1a89b393105b8e5986a22a2" }
rmp-serde = { git = "https://github.com/kornelski/msgpack-rust", rev = "1a05988fb11d73d2e1a89b393105b8e5986a22a2" }

[patch.'https://gitlab.com/crates.rs/crate_db.git']
crate_db = { path = "crate_db" }

[patch.'https://gitlab.com/crates.rs/crate_files.git']
crate_files = { path = "crate_files" }

[patch.'https://gitlab.com/crates.rs/crate_git_checkout.git']
crate_git_checkout = { path = "crate_git_checkout" }

[patch.'https://gitlab.com/crates.rs/crates_io_client.git']
crates_io_client = { path = "crates_io_client" }

[patch.'https://gitlab.com/crates.rs/docs_rs_client.git']
docs_rs_client = { path = "docs_rs_client" }

[patch.'https://gitlab.com/crates.rs/front_end.git']
front_end = { path = "front_end" }

[patch.'https://gitlab.com/crates.rs/github_info.git']
github_info = { path = "github_info" }

[patch.'https://gitlab.com/crates.rs/render_readme.git']
render_readme = { path = "render_readme" }

[patch.'https://gitlab.com/crates.rs/repo_url.git']
repo_url = { path = "repo_url" }

[patch.'https://gitlab.com/crates.rs/simple_cache.git']
simple_cache = { path = "simple_cache" }

[patch.'https://gitlab.com/crates.rs/user_db.git']
user_db = { path = "user_db" }

[patch.'https://gitlab.com/crates.rs/udedokei.git']
udedokei = { path = "udedokei" }
