[package]
edition = "2018"
name = "docs_rs_client"
version = "0.4.0"
authors = ["Kornel <kornel@geekhood.net>"]

[lib]
name = "docs_rs_client"
path = "src/lib_docs_rs_client.rs"

[dependencies]
quick-error = "1.2.2"
serde = "1.0.104"
serde_json = "1.0.44"
serde_derive = "1.0.104"
simple_cache = { git = "https://gitlab.com/crates.rs/simple_cache.git", version = "0.7.0" }
