[package]
version = "0.7.0"
edition = "2018"
name = "crates_io_client"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Unofficial, minimal client that gets data from crates.io internal JS API"

[lib]
name = "crates_io_client"
path = "src/lib_crates_io_client.rs"

[dependencies]
serde = "1.0.45"
serde_derive = "1.0.45"
simple_cache = { git = "https://gitlab.com/crates.rs/simple_cache.git", version = "0.7.0" }
chrono = "0.4.3"
rand = "0.6"
semver = "0.9.0"
mysteriouspants-throttle = "0.2.5"
parking_lot = "0.7.1"
