[package]
edition = "2018"
name = "front_end"
version = "0.3.1"
authors = ["Kornel <kornel@geekhood.net>"]
autobins = true

[lib]
name = "front_end"
path = "src/front_end.rs"

[build-dependencies]
ructe = "0.5.6"

[dependencies]
kitchen_sink = { git = "https://gitlab.com/crates.rs/kitchen_sink.git", version = "0.6.0" }
rich_crate = { git = "https://gitlab.com/crates.rs/rich_crate.git", version = "0.3.3" }
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git", version = "0.5.0" }
categories = { git = "https://gitlab.com/crates.rs/categories.git" }
udedokei = { git = "https://gitlab.com/crates.rs/udedokei.git" }
search_index = { git = "https://gitlab.com/crates.rs/search_index.git" }
rayon = "1.0.3"
failure = "0.1.2"
chrono = "0.4.2"
semver = "0.9.0"
semver-parser = "0.9.0"
lab = "0.6.0"
urlencoding = "1.0.0"
regex = "1.0.0"
locale = "0.2.2"
url = "1.7.1"
