array_width = 120
binop_separator = "Back"
chain_width = 120
comment_width = 222
condense_wildcard_suffixes = true
edition = "2021"
enum_discrim_align_threshold = 5
fn_args_layout = "Compressed"
fn_params_layout = "Compressed"
fn_call_width = 120
fn_single_line = true
force_explicit_abi = false
imports_granularity = "Module"
imports_layout = "Horizontal"
match_block_trailing_comma = true
max_width = 160
overflow_delimited_expr = true
reorder_impl_items = true
struct_lit_width = 40
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
