use_small_heuristics = "Max"
binop_separator = "Back"
comment_width = 180
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
where_single_line = true
# merge_imports = true
match_block_trailing_comma = true
max_width = 160
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
overflow_delimited_expr = true
