[package]
version = "0.7.5"
edition = "2018"
name = "simple_cache"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Minimal wrapper for a HTTP client to cache results on disk, forever"
license = "CC0-1.0"

[dependencies]
reqwest = "0.10.4"
quick-error = "1.2.3"
serde_json = "1.0.52"
serde = "1.0.107"
rusqlite = "0.23.1"
thread_local = "1.0.1"
tempfile = "3.1.0"
rmp-serde = "0.14.3"
flate2 = "1.0.14"
parking_lot = "0.10.2"
ahash = "0.3.4"
tokio = { version = "0.2.20", features = ["macros", "sync"] }
