[package]
edition = "2018"
description = "Analyze git repository containing Cargo crates"
name = "crate_git_checkout"
version = "0.4.4"
authors = ["Kornel <kornel@geekhood.net>"]

[lib]
name = "crate_git_checkout"
path = "src/crate_git_checkout.rs"

[dependencies]
git2 = "0.12"
cargo_toml = "0.8.0"
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git" }
repo_url = { path = "../repo_url" }
failure = "0.1.6"
urlencoding = "1.0.0"
lazy_static = "1.4.0"
