[package]
name = "feat_extractor"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"

[dependencies]
rake = { git = "https://github.com/kornelski/rake-rs" }
rich_crate = { path = "../rich_crate" }
lazy_static = "1.4.0"
