[package]
name = "github_v3"
description = "Async GitHub API v3 client"
version = "0.3.0"
authors = ["Kornel <kornel@geekhood.net>"]
keywords = ["github", "rest-api", "async"]
categories = ["web-programming", "web-programming::http-client"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.1", features = ["json"] }
serde = "1.0.104"
serde_json = "1.0.47"
thiserror = "1.0.10"
serde_derive = "1.0.104"
futures = "0.3.4"
async-stream = "0.2.1"
tokio = { version = "0.2.11", features = ["time"] }

[dev-dependencies]
tokio = { version = "0.2.11", features = ["rt-threaded", "macros", "time"] }

[features]
default = ["gzip"]
gzip = ["reqwest/gzip"]
