[package]
edition = "2018"
name = "rich_crate"
version = "0.5.0"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Crate struct enriched with additional crates.rs metadata"
license = "Apache-2.0 OR MIT"

[dependencies]
crates-index = "0.13.1"
crates_io_client = { git = "https://gitlab.com/crates.rs/crates_io_client.git", version = "0.7.0" }
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git", version = "0.6.0" }
categories = { path = "../categories" }
udedokei = { path = "../udedokei" }
cargo_author = "1.0.0"
cargo_toml = "0.8.0"
repo_url = { git = "https://gitlab.com/crates.rs/repo_url.git" }
semver = "0.9.0"
parse_cfg = "2.0.0"
serde_derive = "1.0.70"
serde = "1.0.70"
