[package]
name = "ranking"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"

[lib]
name = "ranking"
path = "src/lib_ranking.rs"

[dependencies]
rayon = "1.0.3"
kitchen_sink = { path = "../kitchen_sink", version = "0.7.0" }
rich_crate = { path = "../rich_crate" }
fxhash = "0.2.1"
chrono = "0.4.6"
