[package]
name = "ranking"
version = "0.1.1"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"

[lib]
name = "ranking"
path = "src/lib_ranking.rs"

[dependencies]
rayon = "1.0.3"
rich_crate = { path = "../rich_crate" }
fxhash = "0.2.1"
chrono = "0.4.6"
cargo_toml = "0.7"
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git", version = "0.6.1" }
semver = "0.9.0"
