[package]
name = "crates-server"
version = "0.9.0"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"
description = "Crates.rs web server"
readme = "README.md"

[package.metadata.deb]
assets = [
    ["target/release/crates-server", "usr/bin/", "755"],
    ["../data/page/*", "/var/lib/crates-server/page/", "644"],
    ["../data/git_crates.txt", "/var/lib/crates-server/", "644"],
    ["../builder/docker/*", "/var/lib/crates-server/", "755"],
]

[dependencies]
actix-web = "2"
env_logger = "0.7"
log = "0.4.6"
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git", version = "0.6.1" }
search_index = { path = "../search_index" }
repo_url = { path = "../repo_url" }
kitchen_sink = { path = "../kitchen_sink", version = "0.8" }
front_end = { path = "../front_end", version = "0.3.4" }
urlencoding = "1.0.0"
failure = "0.1.5"
tokio = { version = "0.2.11", features = ["time"] }
categories = { path = "../categories" }
rayon = "1.3.0"
arc-swap = "0.4.4"
signal-hook = "0.1.12"
locale = "0.2.2"
cap = "0.1"
actix-rt = "1.0.0"
futures = "0.3.1"
actix-files = "0.2.1"
actix-threadpool = "0.3.1"
either = "1.5.3"
