[package]
name = "crates-server"
version = "0.1.13"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"
description = "Crates.rs web server"
readme = "README.md"

[package.metadata.deb]
assets = [
    ["target/release/crates-server", "usr/bin/", "755"],
]

[dependencies]
actix-web = "0.7.16"
env_logger = "0.6.0"
log = "0.4.6"
futures-cpupool = "0.1.8"
futures = "0.1.25"
render_readme = { git = "https://gitlab.com/crates.rs/render_readme.git", version = "0.6.1" }
search_index = { path = "../search_index" }
kitchen_sink = { path = "../kitchen_sink", version = "0.7.3" }
front_end = { path = "../front_end", version = "0.3.2" }
urlencoding = "1.0.0"
failure = "0.1.5"
tokio = "0.1.11"
tokio-timer = "0.2.10"
categories = { path = "../categories" }
