[package]
name = "datadump"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"

[dependencies]
csv = "1.1.1"
tar = "0.4.26"
libflate = "0.1.27"
serde = "1.0.104"
serde_derive = "1.0.104"
chrono = "0.4.10"
kitchen_sink = { path = "../kitchen_sink", version = "0.8" }

