[build]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/x86_64-linux-gnu-gcc"
rustflags = ["--cfg", "tokio_unstable"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native", "--cfg", "tokio_unstable"]
