[package]
edition = "2018"
name = "crate_db"
version = "0.4.6"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Internal index of crates used by crates.rs"

[lib]
name ="crate_db"
path = "src/lib_crate_db.rs"

[dependencies]
rusqlite = "0.21.0"
rich_crate = { path = "../rich_crate" }
categories = { path = "../categories" }
failure = "0.1.6"
rayon = "1.3.0"
lazy_static = "1.4.0"
chrono = "0.4.10"
thread_local = "1.0.0"
parking_lot = "0.10.0"
rake = { git = "https://github.com/kornelski/rake-rs" }
rmp-serde = "0.14.0"
heck = "0.3.1"
semver = "0.9.0"
tokio = { version = "0.2.11", features = ["sync", "macros", "rt-threaded"] }

[dev-dependencies]
tempfile = "3.1.0"
cargo_toml = "0.8.0"
