[package]
edition = "2018"
name = "crate_db"
version = "0.4.6"
authors = ["Kornel <kornel@geekhood.net>"]
description = "Internal index of crates used by crates.rs"

[lib]
name ="crate_db"
path = "src/lib_crate_db.rs"

[dependencies]
rusqlite = "0.20"
rich_crate = { path = "../rich_crate" }
categories = { path = "../categories" }
failure = "0.1.3"
rayon = "1.0.1"
lazy_static = "1.0.0"
chrono = "0.4.2"
thread_local = "1"
parking_lot = "0.9"
rake = { git = "https://github.com/kornelski/rake-rs" }
rmp-serde = "0.14"
heck = "0.3.1"
semver = "0.9.0"

[dev-dependencies]
tempfile = "3.1.0"
cargo_toml = "0.8.0"
