[package]
name = "_"
version = "0.0.0"

[lib]
path = "/dev/null"

[dependencies]
arrayvec = "*"
bincode = "*"
bindgen = "*"
bitflags = "*"
byteorder = "*"
bytes = "*"
cc = "*"
chrono = "*"
clap = "*"
cmake = "*"
curl = "*"
dtoa = "*"
either = "*"
error-chain = "*"
failure = "*"
fnv = "*"
git2 = "*"
glob = "*"
hyper = "*"
itertools = "*"
lazy_static = "*"
libc = "*"
log = "*"
num = "*"
num-traits = "*"
ordermap = "*"
parking_lot = "*"
phf = "*"
quote = "*"
rand = "*"
rayon = "*"
regex = "*"
reqwest = "*"
scopeguard = "*"
semver = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha2 = "*"
structopt = "*"
syn = "*"
tar = "*"
tokio = "*"
