[package]
name = "debcargo_list"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.15"
quick-error = "2.0.0"
