[package]
version = "0.3.4"
edition = "2018"
name = "search_index"
authors = ["Kornel <kornel@geekhood.net>"]

[lib]
name = "search_index"
path = "src/lib_search_index.rs"

[dependencies]
tantivy = "0.15.0"
rich_crate = { path = "../rich_crate" }
rayon = "1.5.0"
rand = "0.8"
