[package]
version = "0.3.2"
edition = "2018"
name = "search_index"
authors = ["Kornel <kornel@geekhood.net>"]

[lib]
name = "search_index"
path = "src/lib_search_index.rs"

[dependencies]
tantivy = "0.10"
rich_crate = { path = "../rich_crate" }
rayon = "1.0.3"
rand = "0.7"
