[package]
name = "creviews"
version = "0.1.3"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2021"

[dependencies]
crev-lib = "0.23.1"
crev-data = "0.23.0"
crev-wot = "0.23.0"
rustsec = { git = "https://github.com/rustsec/rustsec" }
