[package]
name = "creviews"
version = "0.1.3"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"

[dependencies]
crev-lib = "0.19.1"
crev-data = "0.19.0"
crev-wot = "0.19.0"
failure = "0.1.8"
