[package]
name = "creviews"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2018"

[dependencies]
crev-lib = { git = "https://github.com/crev-dev/cargo-crev", rev = "33f412210373cbcb92287441fabee7d16af55b17" }
crev-data = { git = "https://github.com/crev-dev/cargo-crev", rev = "33f412210373cbcb92287441fabee7d16af55b17" }
crev-wot = { git = "https://github.com/crev-dev/cargo-crev", rev = "33f412210373cbcb92287441fabee7d16af55b17" }
failure = "0.1.8"
