[package]
edition = "2018"
name = "kitchen_sink"
version = "0.8.1"
authors = ["Kornel <kornel@geekhood.net>"]
publish = false

[lib]
name = "kitchen_sink"
path = "src/lib_kitchen_sink.rs"

[dependencies]
crates-index = "0.13.1"
crates_io_client = { git = "https://gitlab.com/crates.rs/crates_io_client.git", version = "0.7.0" }
docs_rs_client = { git = "https://gitlab.com/crates.rs/docs_rs_client.git", version = "0.4.0" }
github_info = { path = "../github_info", version = "0.8.0" }
crate_git_checkout = { git = "https://gitlab.com/crates.rs/crate_git_checkout.git", version = "0.4.3" }
user_db = { path = "../user_db", version = "0.3" }
crate_db = { path = "../crate_db", version = "0.4.0" }
categories = { path = "../categories" }
render_readme = { path = "../render_readme" }
rich_crate = { path = "../rich_crate", version = "0.5" }
simple_cache = { git = "https://gitlab.com/crates.rs/simple_cache.git", version = "0.7.0" }
lazyonce = "1.0.0"
repo_url = { git = "https://gitlab.com/crates.rs/repo_url.git", version = "0.3.0" }
cargo_toml = "0.8"
serde = "1.0.43"
serde_derive = "1.0.70"
serde_json = "1.0.33"
toml = "0.5"
lazy_static = "1.0.0"
regex = "1.1.0"
url = "2.1"
failure = "0.1.2"
lazycell = "1.2.1"
rayon = "1.0.3"
reqwest = "0.9"
tokio = "0.1.11"
itertools = "0.8"
semver-parser = "0.9.0"
chrono = "0.4.5"
semver = "0.9.0"
ctrlc = "3.1.1"
flate2 = "1.0.6"
string-interner = "0.7.0"
parking_lot = "0.9"
udedokei = { path = "../udedokei" }
tar = "0.4.15"
libflate = "0.1.14"
ahash = "0.2.12"
deunicode = "1.0.0"

